In [90]:
import numpy as np

In [91]:
beta = np.array([[1.0,1.0,1.0,1.0],[1.0,1.0,1.0,1.0]])
x = np.array([1.0,1.0,1.0,1.0])
alpha = np.array([1.0,1.0])

In [92]:
def compute_gradient_matrix_cookbook(x,alpha,beta):
    return 2*(np.dot(beta,np.outer(x,x.T)).T - (np.outer(x,alpha)))

In [93]:
def compute_difference(beta,x):
    alpha_hat = (beta).dot(x)
    difference = alpha_hat-alpha
    
    return difference

In [94]:
def sse(difference):
    return (difference.T).dot(difference) 

In [95]:
def compute_gradient_manual(beta,x,index_values,delta=0.00001):
    row,col = index_values
    difference1 = compute_difference(beta,x)
    
    beta_copy = beta.copy()
    beta_copy[row,col]+=0.00001
    
    difference2 = compute_difference(beta_copy,x)
    
    return (sse(difference1)-sse(difference2))/0.001

In [77]:
alpha_hat = (beta).dot(x)
difference = alpha_hat-alpha

In [79]:
#cookbook gradient
gradient(x,alpha,beta)

array([[6., 6.],
       [6., 6.],
       [6., 6.],
       [6., 6.]])

In [96]:
#manual gradient verification

gradient_matrix_manual = np.zeros(beta.shape)

for val in range(len(beta)):
    for valtwo in range(len(beta[0])):
        partial_gradient = compute_gradient_manual(beta,x,(val,valtwo))
        gradient_matrix_manual[val,valtwo]=partial_gradient
        
gradient_matrix_manual.T

array([[-0.0600001, -0.0600001],
       [-0.0600001, -0.0600001],
       [-0.0600001, -0.0600001],
       [-0.0600001, -0.0600001]])

In [87]:
for val in range(len(beta)):
    for valtwo in range(len(beta[0])):
        partial_gradient = compute_gradient_manual(beta,x,(val,valtwo))
        gradient_matrix_manual[val,valtwo]=partial_gradient

In [89]:
gradient_matrix_manual.T

array([[-6.001, -6.001],
       [-6.001, -6.001],
       [-6.001, -6.001],
       [-6.001, -6.001]])